server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak_trial
    username: adi
    password: adithya123
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-backend
            client-secret: "TlEPoVHGpfXbNoAPzotc54J8KGqE8sVR"
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo-realm
            authorization-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/certs

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm

jwt:
  auth:
    converter:
      resource-id: spring-backend
      principle-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG

authentication-type: "implicit"
